### ISSUE TITLE
hdfsMove() and hdfsCopy() not implemented

### ISSUE THREAD

**Issue by wouterdebie** [PivotalRD/libhdfs3#13]
Both hdfsMove() and hdfsCopy() are specified in `client/hdfs.h`, but don't have an implementation in `client/Hdfs.cpp`.
I'm trying to build a python wrapper using Swig and not having implementations breaks my build. As far as I know, a move operation is a rename operation, so that should just be an alias.

**Comment by wangzw** [comment]
Thanks for your feedback, I will fix it.

**Comment by MKnowledger** [comment]
it seems not fixed
