### ISSUE TITLE
hdfsListDirectory returns mLastMod in milliseconds 

### ISSUE THREAD

**Issue by dtmadko** [PivotalRD/libhdfs3#14]
According to hdfs.h 

 tTime mLastMod; /* the last modification time for the file in seconds */

But the values returned by hdfsListDirectory are in ms. 

it can be easily fixed -- This is what is done in JNI bases hdfs library: fileInfo->mLastMod = jVal.j / 1000;

**Comment by wangzw** [comment]
Nice catch, I will fix it.
