### ISSUE TITLE
For directory listing, do not append the source path.

### ISSUE THREAD

**Issue by m-ishaque** [PivotalRD/libhdfs3#15]
Specifically this line in RpcHelper.h:

fs.setPath((src + "/" + proto.path()).c_str());

I have written a fuse client using libhdfs3, and for directory listings it seems that kernel prefers just the names in the directory. Of course, I can parse the listing myself (to separate out name from the path), however, it seems to me that src is already available to the caller of getListing, thus it seems reasonable to leave the appending to caller.

Let me know what you think. I can submit a pull request.

**Comment by wangzw** [comment]
libhdfs keeps the full path in the result of getListing (correct me if I am wrong), libhdfs3 should keep the same behaviors with libhdfs.

If let me design the interface, I will only store the name instead of full path.

**Comment by m-ishaque** [comment]
Fair enough.

Btw, thanks for the code.
