### ISSUE TITLE
Problem communicating with hadoop server

### ISSUE THREAD

**Issue by jamesReward** [PivotalRD/libhdfs3#18]
Hi there,

I'm pretty excited about using libhdfs3, but having problems authenticating with my local hadoop server.  I don't have administrator privileges on it, or a lot of transparency on the install for that matter, but I do know that it's running a Hadoop 2.6.0 build with (I think) protobuf 2.5.0.

I'm getting this error:

2015-09-03 13:15:38.962745, p114445 th139816236222784, ERROR Failed to invoke RPC call "getFsStats" on server "server_name_removed:port":
RpcChannel.cpp: 413: HdfsRpcException: Failed to invoke RPC call "getFsStats" on server "server_name_removed:port"
 @ Hdfs::Internal::RpcChannelImpl::invokeInternal(std::shared_ptr<Hdfs::Internal::RpcRemoteCall>)
 @ Hdfs::Internal::RpcChannelImpl::invoke(Hdfs::Internal::RpcCall const&)
 ...
Caused by SaslClient.cpp: 84: HdfsIoException: Cannot initialize client (2) : Unknown SASL mechanism
... 

This hadoop package is pretty old I suspect, but I built libhdfs using protobuf 2.5.0 and the latest libgsasl and libuuid, so I'm not sure how important having those match the hadoop package is.  Do you think that's a problem?  Any ideas on how to troubleshoot and fix this?  Thanks.

**Comment by wangzw** [comment]
Hi

It an issue of libgsasl. To solve this issue, you should rebuild libgsasl to support gssapi.

```
cd libgsasl-<version>
./configure --with-gssapi-impl=mit
make install
```
