### ISSUE TITLE
number of rpc connections per application

### ISSUE THREAD

**Issue by spothineni** [PivotalRD/libhdfs3#29]
starting a new thread:

I am trying to read thousands of files from hdfs using libhdfs3, do I need to make just one connection with hdfsBuilderConnect and reuse it throughout the application? or is that ok to make connection per every file and close it?

**Comment by visierl** [comment]
I haven't tried this with thousands of files, but I would think that you 
could do it either way.  There may be a cost to making a connection for 
each file versus re-using the connection on each successive file and 
closing it at the end.

I would suggest writing a simple test case with lots of files and trying 
it both ways, see which one works better for you.

Eric

**Comment by spothineni** [comment]
Thanks Eric, will try and post it again here

**Comment by wangzw** [comment]
Using one connection for your application to reduce memory usage and reuse RPC connection, FileSystem object is thread safe, but File is not. Do not share File between threads.

Reading thousands of files concurrently in one process is ok since Apache HAWQ do the same thing.
