### ISSUE TITLE
Build problem under Ubuntu12.04

### ISSUE THREAD

**Issue by xunzhang** [PivotalRD/libhdfs3#30]
I `bootstrap` successfully, but during `make`, I got an error below:
`/home/xxx/tmp/libhdfs3/src/common/Logger.cpp:50:31: error: 'Hdfs::Internal::Once' cannot be thread-local because it has non-trivial type 'std::once_flag'`. What's the problem here?

**Comment by wangzw** [comment]
what os and complier do you use?

**Comment by xunzhang** [comment]
@wangzw ubuntu12.04, gcc 4.7.3.

**Comment by wangzw** [comment]
Seems that your complier cannot support thread-local non-trivial variable. You may solve this issue by building with boost.

run ./bootstrap --enable-boost

The CI of this project is running on ubuntu14.04 both with and without boost. And all tests passed.

**Comment by xunzhang** [comment]
Thanks, it works! You mean gcc do not support thread-local non-trivial variable, then the code `hdfs::internal::once` will check out boost to find the right type?

**Comment by wangzw** [comment]
Yes. It will use boost instead of std::once_flag.

I cannot find a ubuntu source to install gcc 4.7.3 on ubuntu 12.04.  If you complier gcc by yourself, you may check it.

**Comment by xunzhang** [comment]
I will check it later and with this issue it does not relate to `libhdfs3` itself. Thanks.
