### ISSUE TITLE
lack of -lkrb5

### ISSUE THREAD

**Issue by itismewxg** [PivotalRD/libhdfs3#4]
in the link.txt for Unittest and function test, we have to link to krb5, lack of this flag:

-lkrb5

**Comment by wangzw** [comment]
Link flags are auto generated by CMake, so it may be a CMake issue. Which CMake version are you using?

Here is a CI which is running on travis-ci.org. It only run unit test but unit test works well.
https://travis-ci.org/PivotalRD/libhdfs3/builds/42713132
