### ISSUE TITLE
Support windows

### ISSUE THREAD

**Issue by thanhdowisc** [PivotalRD/libhdfs3#5]
libhdfs3 should compile and run smoothly on windows.

**Comment by wangzw** [comment]
Hi Thanh

Would you please create a new branch for windows and merger to apache-rpc-9 branch finally?
Current code in apache-rpc-9 branch is stable and fully tested in Pivotal internal. I'd like to keep it stable and others can use it directly.

Thanks.
Zhanwei Wang

**Comment by thanhdowisc** [comment]
Yes, definitely.

**Comment by thanhdowisc** [comment]
Just bootstrap a new branch for win
