### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by thanhdowisc** [PivotalRD/libhdfs3#8]
Hey Zhanwei,

For new code that we add, I think it would be best that we follow the google coding style
http://google-styleguide.googlecode.com/svn/trunk/cppguide.html

For old code, we can gradually restructure it later, but it is not a priority.

What do you think?

Thanks,
Thanh

**Comment by wangzw** [comment]
Hi Thanh

I used to use [astyle](http://astyle.sourceforge.net/) to format the style with the following command line.

    astyle --style=attach --indent=spaces=4 --indent-preprocessor --break-blocks --pad-oper --pad-header --unpad-paren --delete-empty-lines --suffix=none --align-pointer=middle --lineend=linux --indent-col1-comments

But I currently use [clang-format](http://clang.llvm.org/docs/ClangFormat.html) to format code to google style.

Google style is now my favorite but we have to decide one thing ``` indent ```

In google style the indent is 2 space by default. Should we keep it to 4 or change the indent to 2 in new source files? I suggest that we keep the indent with 4 space in new files. what is you opinion?

**Comment by thanhdowisc** [comment]
Zhanwei.

Although keeping 4-space indented in new files make it compatible with the old code, which is already 4-space indented, I am afraid that it may create a "style-maintenance" headache, because our style would be something like "Google style with 4 space indent" :)

I suggest we stick strictly to the Google Style (using 2-space indent, etc.) because this will make style maintenance easier and minimize the number of style exceptions that we may need to keep in mind all the time (i.e., oh it is Google style with a few exception of A, B, and C).

**Comment by wangzw** [comment]
Cool! Let's using Google Style.

I suggest that we use ```clang-format``` to format new files. You can download ```clang-format``` binary for windows from [this page](https://packagecontrol.io/packages/Clang%20Format)

And [this eclipse plugin](https://github.com/wangzw/CppStyle) is helpful if you use eclipse.

**Comment by thanhdowisc** [comment]
+1, will try out clang-format.
